'**************************************************************************************************
'
' Filename: LibraryManager.txt
' Author: srichs
' Date Created: 28 Oct 2020
' Purpose: Creates a UML Class Diagram for LibraryManager using PlantUML.
' 
'**************************************************************************************************


@startuml LibraryManager

'--------------------------------------- skinparam settings ---------------------------------------
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    FontSize 16
    AttributeIconSize 0
    AttributeFontSize 14
    'HeaderBackgroundColor LightGrey
}
skinparam shadowing false
hide circle
'skinparam handwritten true
'------------------------------------- end skinparam settings -------------------------------------


'-------------------------------------------- classes --------------------------------------------
class LibraryManager {
    +{static}main(String[]) : void
}

class Book {
    -title : String
    -author : String
    -yearPublished : String
    -iSBN : String
    -deweyDecimal : String
    -isChecked : String

    +toString() : String
}
'note left of LibraryManager: This is the LibraryManager Class
'------------------------------------------ end classes ------------------------------------------


'------------------------------------------ connections ------------------------------------------
LibraryManager -- Book
'---------------------------------------- end connections ----------------------------------------

@enduml